### ISSUE TITLE
Inject HttpClientFactory in AppHostBase

### ISSUE THREAD

**Issue by matmaneff** [NetCoreApps/LiveDemos#1]
I am working with the AppHostBase class to implement Redis MQ. I need to inject the IHttpClientFactory class I see that the class to be overloaded Configure (Container container) that inherits from IServiceProvider DOES NOT have the IServiceCollection Add.HttpClient method.
When I run my application that has a service that injects IHttpClientFactory, it gives me an error indicating that Factory is missing.
How do I solve this problem since the injection is done within the Configure method

<img width="341" alt="redis" src="https://user-images.githubusercontent.com/86027919/126528471-f89cfcee-cfc9-47ab-904f-446f5b388e9a.PNG">

**Comment by mythz** [comment]
I've already answered this on https://stackoverflow.com/a/68473047/85785

If you're a customer please ask general support questions in the Customer Forums https://forums.servicestack.net otherwise please continue to use StackOverflow.
